# Generated by Django 3.2 on 2023-01-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbData',
            fields=[
                ('Categories', models.TextField(blank=True)),
                ('Price', models.FloatField(blank=True)),
                ('Reviews', models.TextField(blank=True)),
                ('Rating', models.TextField(blank=True)),
                ('Hosted_By', models.TextField(blank=True)),
                ('Description', models.TextField(blank=True)),
                ('URL', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Amenities', models.TextField(blank=True)),
                ('HouseRule', models.TextField(blank=True)),
                ('Location', models.TextField(blank=True)),
                ('SafetyProperty', models.TextField(blank=True)),
                ('Image', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'airbnbData',
            },
        ),
    ]
