# Generated by Django 3.2 on 2023-01-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_airbnbdata_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbnbdata',
            name='URL',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
